src = $(wildcard *.c) $(wildcard */*.c)
obj = $(src:.c=.so)

LDFLAGS  = -lczmq 
CFLAGS   = -shared $(EXTCFLAGS) -fPIC -O3

zeromq: 
	$(CC) -o $@.so $(src) $(LDFLAGS) $(CFLAGS)

.PHONY: clean
clean:
	rm -f $(obj) 

.PHONY: install
install: zeromq
	cp zeromq.so ../lib/zeromq.so
	make -f Makefile.linux clean 
	